import{S as c,i}from"./assets/vendor-46aac873.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const l="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEpSURBVHgBrZXtEcIgDIZTzp5/3URHcSPpJLpBXcVd+FPwiqQt1y+SUNv3DuUkvA+0SQQg5Jx7WOt8zsBYyudEmXsPuijg3bbtB1ipa/jQYQ+UZVmBpHjyprEvyBTGSjf52zwbssdchBxhTkI4c2vtTTJMxcwgw6RObZReXDycMSYBcTWuQX/6RqcMQpCmIOPNHbG30SKAgkjmU8AJBJ3PpQ5GOO2KCYVFGEaFa9J+EbCEDIAsc5SCTCkFPjWXlHWD2Jvw5MNP2b1HBEzN42OZvhMRwmURly1cCvfrszSlC41PxR6SKjQs3g4Qg6z9PpdBxsitIhWDXrPDcZCtWplHHQEhzY+AiOZ7IJz5qg5iWygK/wjfFwD+T18pdfXe37e0j07jTeTBPZYfWztI8097RKsAAAAASUVORK5CYII=";document.addEventListener("submit",A);function f(t){const o="https://pixabay.com/api/",n="?",s=new URLSearchParams({key:"42187332-ff85343869753156c1a8d7a61",q:`${t}`,image_type:"photo",orientation:"horizontal",safesearch:"true"}),e=o+n+s;return fetch(e).then(r=>{if(!r.ok)throw new Error("Network response was not ok");return r.json()}).catch(r=>{throw console.error(r),new Error("Error fetching images from the server")})}const m={captionsTitle:"attr",captionsData:"alt"},p=new c(".gallery a",m);function g(){const t=document.getElementById("loader");t.style.display="block",document.querySelector(".gallery").innerHTML=""}function u(){const t=document.getElementById("loader");t.style.display="none"}function A(t){t.preventDefault();const o=t.target.elements.name.value;if(o.trim().length===0){i.error({message:"Please enter a valid search term!",position:"topRight",messageColor:"#fafafb",backgroundColor:"#ef4040",iconUrl:l,iconColor:"#ffffff"});return}g(),f(o).then(n=>{o.length>0&&n.hits.length>0?(y(n.hits),p.refresh()):i.error({message:"Sorry, there are no images matching<br> your search query. Please try again!",position:"topRight",messageColor:"#fafafb",backgroundColor:"#ef4040",iconUrl:l,iconColor:"#ffffff"})}).finally(()=>{u(),t.target.reset()})}function d({webformatURL:t,largeImageURL:o,tags:n,likes:s,views:e,comments:r,downloads:a}){return`<li class="gallery-item">
  <a class="gallery-link" href="${o}">
    <img
      class="gallery-image"
      src="${t}" 
      alt="${n}"
    >
        <div class="all-image-info">
    <p class="image-info"><span class="property-name">Likes</span>${s}</p>
        <p class="image-info"><span class="property-name">Views</span>${e}</p>
            <p class="image-info"><span class="property-name">Comments</span>${r}</p>
                <p class="image-info"><span class="property-name">Downloads</span>${a}</p>
                </div>
    </a>
  </li>`}function h(t){return t.map(d).join("")}function y(t){const o=h(t);document.querySelector(".gallery").innerHTML=o}
//# sourceMappingURL=commonHelpers.js.map
