import{S as c,i}from"./assets/vendor-46aac873.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const l="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEpSURBVHgBrZXtEcIgDIZTzp5/3URHcSPpJLpBXcVd+FPwiqQt1y+SUNv3DuUkvA+0SQQg5Jx7WOt8zsBYyudEmXsPuijg3bbtB1ipa/jQYQ+UZVmBpHjyprEvyBTGSjf52zwbssdchBxhTkI4c2vtTTJMxcwgw6RObZReXDycMSYBcTWuQX/6RqcMQpCmIOPNHbG30SKAgkjmU8AJBJ3PpQ5GOO2KCYVFGEaFa9J+EbCEDIAsc5SCTCkFPjWXlHWD2Jvw5MNP2b1HBEzN42OZvhMRwmURly1cCvfrszSlC41PxR6SKjQs3g4Qg6z9PpdBxsitIhWDXrPDcZCtWplHHQEhzY+AiOZ7IJz5qg5iWygK/wjfFwD+T18pdfXe37e0j07jTeTBPZYfWztI8097RKsAAAAASUVORK5CYII=";document.addEventListener("submit",A);function f(o){const r="https://pixabay.com/api/",s="?",n=new URLSearchParams({key:"42187332-ff85343869753156c1a8d7a61",q:`${o}`,image_type:"photo",orientation:"horizontal",safesearch:"true"}),e=r+s+n;return fetch(e).then(t=>t.json())}const p={captionsTitle:"attr",captionsData:"alt"},g=new c(".gallery a",p);function m(){const o=document.getElementById("loader");o.style.display="block"}function u(){const o=document.getElementById("loader");o.style.display="none"}function A(o){o.preventDefault();const r=o.target.elements.name.value;console.log(r),m(),setTimeout(()=>{f(r).then(s=>{s.hits.length>0?(console.log(s.hits),h(s.hits),g.refresh()):i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",messageColor:"#fafafb",backgroundColor:"#ef4040",iconUrl:l,iconColor:"#ffffff"})}).catch(s=>{i.error({message:"An error occurred while fetching images. Please try again!",position:"topRight",messageColor:"#fafafb",backgroundColor:"#ef4040",iconUrl:l,iconColor:"#ffffff"})}).finally(()=>{u(),o.target.reset()})},1e3)}function d({webformatURL:o,largeImageURL:r,tags:s,likes:n,views:e,comments:t,downloads:a}){return`<li class="gallery-item">
  <a class="gallery-link" href="${r}">
    <img
      class="gallery-image"
      src="${o}" 
      alt="${s}"
    >
        <div class="all-image-info">
    <p class="image-info"><span class="property-name">Likes</span>${n}</p>
        <p class="image-info"><span class="property-name">Views</span>${e}</p>
            <p class="image-info"><span class="property-name">Comments</span>${t}</p>
                <p class="image-info"><span class="property-name">Downloads</span>${a}</p>
                </div>
    </a>
  </li>`}function y(o){return o.map(d).join("")}function h(o){const r=y(o);document.querySelector(".gallery").innerHTML=r}
//# sourceMappingURL=commonHelpers.js.map
